# Tensor Basics

In [1]:
import torch

In [20]:
x = torch.empty(2,2,3)
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -1.4176e-13,  3.0955e-41]],

        [[-3.1550e-14,  3.0955e-41, -8.3674e+02],
         [ 4.5824e-41,  1.4013e-45,  0.0000e+00]]])


In [21]:
x = torch.rand(2,2)
print(x)

tensor([[0.4064, 0.0592],
        [0.1780, 0.4562]])


In [22]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [23]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


### Tensor Details

In [35]:
x = torch.ones(2,2,dtype=torch.float16)
print("Tensor dtype:", x.dtype)
print("Tensor size:", x.size())

Tensor dtype: torch.float16
Tensor size: torch.Size([2, 2])


In [36]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


### Tensor Operations

In [55]:
x = torch.randint(0, 5, (2,))
y = torch.randint(0, 5, (2,))

In [56]:
print("x: ", x)
print("y:", y)

x:  tensor([1, 4])
y: tensor([3, 3])


In [58]:
# z = x + y
z = torch.add(x, y)
print(z)

tensor([4, 7])


In [59]:
# In PyTorch, trailing underscore signifies in-place op.
y.add_(x)
print(y)

tensor([4, 7])


In [60]:
print("x: ", x)
print("y:", y)

x:  tensor([1, 4])
y: tensor([4, 7])


In [63]:
# z = x - y
z = torch.sub(x, y)
print(z)

tensor([-3, -3])


In [64]:
y.sub_(x)
print(y)

tensor([3, 3])


In [65]:
# z = x * y
z = torch.mul(x, y)
print(z)

tensor([ 3, 12])


In [66]:
y.mul_(x)
print(y)

tensor([ 3, 12])


In [68]:
print("x: ", x)
print("y:", y)

x:  tensor([1, 4])
y: tensor([ 3, 12])


### Advanced Operations

**Slicing tensors**

In [71]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8841, 0.9751, 0.9234],
        [0.2452, 0.7758, 0.5056],
        [0.4158, 0.3944, 0.2258],
        [0.6247, 0.0989, 0.0473],
        [0.6611, 0.8358, 0.1755]])


In [72]:
print(x[:])

tensor([[0.8841, 0.9751, 0.9234],
        [0.2452, 0.7758, 0.5056],
        [0.4158, 0.3944, 0.2258],
        [0.6247, 0.0989, 0.0473],
        [0.6611, 0.8358, 0.1755]])


In [74]:
print(x[0, :])

tensor([0.8841, 0.9751, 0.9234])


In [73]:
print(x[:, 0])

tensor([0.8841, 0.2452, 0.4158, 0.6247, 0.6611])


In [75]:
print(x[0, 0])

tensor(0.8841)


In [76]:
print(x[0, 0].item())

0.8840826749801636


**Reshaping tensors**

In [86]:
x = torch.rand(2,3)
print(x)

tensor([[0.9742, 0.0987, 0.7310],
        [0.4212, 0.1334, 0.1215]])


In [88]:
y = x.view(6)
print("y: ", y)
print("size: ", y.size())

y:  tensor([0.9742, 0.0987, 0.7310, 0.4212, 0.1334, 0.1215])
size:  torch.Size([6])


In [89]:
# Putting -1 in place of a dimension tells PyTorch to infer
y = x.view(-1, 3)
print("y: ", y)
print("size: ", y.size())

y:  tensor([[0.9742, 0.0987, 0.7310],
        [0.4212, 0.1334, 0.1215]])
size:  torch.Size([2, 3])


**NumPy and PyTorch Tensors**

In [90]:
import numpy as np

In [103]:
a = torch.ones(5)
print("a:", a)
print("a type: ", type(a))
# If Tensor is on CPU, both objects share same memory location
b = a.numpy()
print("b:", b)
print("b type: ", type(b))

a: tensor([1., 1., 1., 1., 1.])
a type:  <class 'torch.Tensor'>
b: [1. 1. 1. 1. 1.]
b type:  <class 'numpy.ndarray'>


In [102]:
a = np.ones(5)
print("a:", a)
print("a type: ", type(a))
b = torch.from_numpy(a)
print("b:", b)
print("b type: ", type(b))

a: [1. 1. 1. 1. 1.]
a type:  <class 'numpy.ndarray'>
b: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
b type:  <class 'torch.Tensor'>


### CPU & GPU

In [105]:
if torch.cuda.is_available():
    print(True)

True


In [106]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [108]:
# However, numpy can only handle CPU tensors
z.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [109]:
z = z.to("cpu")
z.numpy()

array([2., 2., 2., 2., 2.], dtype=float32)