In [8]:
import torch

x = torch.empty(2,2)
print(x)

tensor([[4.5629e-10, 3.0805e-41],
        [4.6521e-10, 3.0805e-41]])


In [7]:
x = torch.rand(2,2)
print(x)

tensor([[0.9290, 0.2076],
        [0.0586, 0.8441]])


In [9]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [10]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [11]:
print(x.dtype)

torch.float32


In [12]:
x = torch.ones(2,2,dtype=torch.double)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.float64


In [13]:
print(x.size())

torch.Size([2, 2])


In [14]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
### Operations

In [17]:
x = torch.ones(2,2)
y = torch.ones(2,2)
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [18]:
z = x + y
print(z)

tensor([[2., 2.],
        [2., 2.]])


In [19]:
z = torch.add(x, y)
print(z)

tensor([[2., 2.],
        [2., 2.]])


In [20]:
# trailing underscore signifies in-place operation
y.add_(x)
print(y)

tensor([[2., 2.],
        [2., 2.]])


In [22]:
y.sub_(x)
print(y)

tensor([[1., 1.],
        [1., 1.]])


In [23]:
z = x - y
print(z)

tensor([[0., 0.],
        [0., 0.]])


In [24]:
z = torch.sub(x, y)
print(z)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
### Mul + Div

In [25]:
z = x * y
print(z)

tensor([[1., 1.],
        [1., 1.]])


In [26]:
z = torch.mul(x, y)
print(z)

tensor([[1., 1.],
        [1., 1.]])


In [27]:
z = x / y
print(z)

tensor([[1., 1.],
        [1., 1.]])


In [28]:
z = torch.div(x, y)
print(z)

tensor([[1., 1.],
        [1., 1.]])


In [29]:
y.mul_(x)
print(y)

tensor([[1., 1.],
        [1., 1.]])


In [30]:
y.div_(x)
print(y)

tensor([[1., 1.],
        [1., 1.]])


In [35]:
x = torch.rand(5,3)
print(x)

tensor([[0.4665, 0.9344, 0.9664],
        [0.5403, 0.4765, 0.2870],
        [0.9028, 0.2895, 0.0953],
        [0.1932, 0.4059, 0.6834],
        [0.1044, 0.0906, 0.8327]])


In [36]:
print(x[:, 0])

tensor([0.4665, 0.5403, 0.9028, 0.1932, 0.1044])


In [37]:
print(x[0, :])

tensor([0.4665, 0.9344, 0.9664])


In [38]:
print(x[0, 0])

tensor(0.4665)


In [39]:
print(x[0, 0].item())

0.46648484468460083


In [40]:
x = torch.rand(4,4)
print(x)

tensor([[0.4656, 0.5757, 0.3906, 0.4267],
        [0.5542, 0.5126, 0.7222, 0.7703],
        [0.9791, 0.0358, 0.4922, 0.5487],
        [0.7381, 0.2312, 0.9607, 0.0888]])


In [44]:
y = x.view(16)
print(y.size())

torch.Size([16])


In [45]:
y = x.view(-1, 8)
print(y.size())

torch.Size([2, 8])


In [52]:
import numpy as np

In [50]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [51]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [53]:
# on CPU, tensor and numpy array point to same memory location
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [54]:
print(b)

[2. 2. 2. 2. 2.]


In [57]:
a = np.ones(5)
print(a)
print(type(a))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [58]:
b = torch.from_numpy(a)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [59]:
a += 1
print(a)

[2. 2. 2. 2. 2.]


In [60]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [62]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    
    z = x + y
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [63]:
# numpy can only handle CPU tensors
z.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [65]:
z = z.to("cpu")
z.numpy()

array([2., 2., 2., 2., 2.], dtype=float32)

In [67]:
# requires_grad tells pytorch it will need to
# compute gradients for this tensor during optimization
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
