In [1]:
import torch
torch.manual_seed(1)

### Creating Tensors

In [2]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [3]:
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [10]:
print(V[0])
print(V[0].item())
print(M[0])
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [11]:
x = torch.randn((2,2))
print(x)

tensor([[0.6614, 0.2669],
        [0.0617, 0.6213]])


### Operations

In [14]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1], 0) # default is 0, for row concat.
print(z_1)

tensor([[ 0.4533,  0.2912, -0.8317, -0.5525,  0.6355],
        [-0.3968, -0.6571, -1.6428,  0.9803, -0.0421],
        [-0.8206,  0.3133, -1.1352,  0.3773, -0.2824],
        [-2.5667, -1.4303,  0.5009,  0.5438, -0.4057],
        [ 1.1341, -1.1115,  0.3501, -0.7703, -0.1473]])


In [13]:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
z_2 = torch.cat([x_2, y_2], 1) # column concat is 1
print(z_2)

tensor([[-0.9880, -0.9081,  0.5423, -0.1383,  0.8310, -0.2477, -0.8029,  0.2366],
        [ 0.1103, -2.2590,  0.6067,  0.2857,  0.6898, -0.6331,  0.8795, -0.6842]])


In [18]:
x = torch.randn(2,3)
print(x)

tensor([[ 1.8782, -0.5666,  0.4016],
        [-0.1153,  0.3170,  0.5629]])


In [20]:
print(x.view(1,6))

tensor([[ 1.8782, -0.5666,  0.4016, -0.1153,  0.3170,  0.5629]])


In [21]:
print(x.view(3, -1)) # -1 to infer dimension

tensor([[ 1.8782, -0.5666],
        [ 0.4016, -0.1153],
        [ 0.3170,  0.5629]])


### Computational Graphs & Differentiation
A computational graph tracks the parameters involved in your operations, preserving enough information to compute gradients.

We specify that we want to produce a computational graph with the parameter `requires_grad=True`.

In [23]:
x = torch.tensor([1.,2.,3.], requires_grad=True)
y = torch.tensor([4.,5.,6.], requires_grad=True)
z = x + y
print(z)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [26]:
print(z.grad_fn)

In [27]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [28]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


### Understanding Autograd

In [29]:
x = torch.randn(2,2)
y = torch.randn(2,2)
print(x.requires_grad, y.requires_grad)

False False


In [30]:
z = x + y
print(z.grad_fn)

None


In [31]:
x = x.requires_grad_()
y = y.requires_grad_()
print(x.requires_grad, y.requires_grad)

True True


In [32]:
z = x + y
print(z.grad_fn)

In [33]:
print(z.requires_grad)

True


In [36]:
print(z)

tensor([[ 0.5323, -1.8252],
        [ 1.0779,  1.0059]], grad_fn=<AddBackward0>)


In [35]:
new_z = z.detach()
print(new_z)

tensor([[ 0.5323, -1.8252],
        [ 1.0779,  1.0059]])


In [37]:
print(new_z.grad_fn)

None


### Stop Tracking

In [38]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [39]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False
